


zb_cfg = {"WORKING_HOURS_START": "10:00",
"WORKING_HOURS_END" :"17:30",
"SLOT_STEP_MINUTES" : 15,
"WORKING_WEEKDAYS":  (0, 1, 2, 3, 4, 5),  # Mon=0 ... Sat=5, Sunday=6 is a day off
"BOOKING_HORIZON_DAYS": 30,
"MAX_PENDING_REQUESTS_PER_CLIENT":  1,
"CANCELLATION_COOLDOWN_WINDOW_MINUTES":  5,
"MAX_CANCELLATIONS_PER_COOLDOWN_WINDOW":  3}